#ifndef SISSERVERLIBRARY_GLOBAL_H
#define SISSERVERLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SISSERVERLIBRARY_LIBRARY)
#  define SISSERVERLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SISSERVERLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SISSERVERLIBRARY_GLOBAL_H
